### ISSUE TITLE
Bug fixes on user signup + login (Oct. 7)

### ISSUE THREAD

**Issue by Dhirajk1** [Dhirajk1/CS222-Group85#2]
The backend api seems to very buggy at the moment, so let's iron it out so its works reliability before calling it our frontend

**Comment by Dhirajk1** [comment]
From @AryanMashruwala 
Works:
-Homepage Initialization
-GET Method for Login Page
Doesn't Work:
-Post Method for Login Page
-Internal Server/Hash Error for Logout Page
-Internal Server Error for Signup
Unsure/Might be a Source of Error:
-Load User method required by flask login lib (might be an error with the SQL database)

**Comment by AryanMashruwala** [comment]
All issues regarding bugs with login and signup have been fixed.

**Comment by Dhirajk1** [comment]
Great Work!
