### ISSUE TITLE
Merge Backend Work Together (Oct.4)

### ISSUE THREAD

**Issue by Dhirajk1** [Dhirajk1/CS222-Group85#5]
Make sure all backend code is in one branch (separate from main). Ideally we'll have it set up so that over the weekend everything gets merged in either the `frontend` of `backend` branch and all individual/feature branched are merged away

**Comment by AryanMashruwala** [comment]
Works:
-Homepage Initialization
-GET Method for Login Page
Doesn't Work: 
-Post Method for Login Page
-Internal Server/Hash Error for Logout Page
-Internal Server Error for Signup
Unsure/Might be a Source of Error:
-Load User method required by flask login lib (might be an error with the SQL database)
